### PR TITLE
implement get_attached_[tree/blob]

### PR DESCRIPTION
**Pull request by kgioioso**

### CODE REVIEW

**Comment by yhdengh** [comment]
Given that `get_attached_tree` and `get_attached_blob` does not require things that are not in `wasm_rt_memory_t` or `wasm_rt_externref_table_t`, I think we could directly write the function body in `initcomposer.cc`.

**Comment by kgioioso** [comment]
Meaning it doesn't require things other than size and ref? 

I feel like fixpointapi.cc is much more readable so I would tend to lean towards putting as much functionality in fixpointapi.cc as possible.

**Comment by yhdengh** [comment]
Any function call from the code generated by `initcomposer.cc` to functions in `fixpointapi.cc` are virtual function calls, so that there would be a performance difference.

**Comment by kgioioso** [comment]
> I think we could directly write the function body in `initcomposer.cc`.

done

**Review by yhdengh — APPROVED** [review]
lgtm

**Pull request merged**
