### PR TITLE
implement nullptr

### PR DESCRIPTION
**Pull request by kgioioso**
eval(nullptr) should return nullptr

### CODE REVIEW

**Comment by keithw** [comment]
Hmm, I'm curious why! What's the purpose of a "null" Name?

**Comment by kgioioso** [comment]
There's nothing stopping create_tree_rw_table_x from having a nullptr in it.

In the long term, we may want to enforce that strict trees cannot have nullptrs (and thus trap if eval is called on a nullptr). But currently, we have not implemented laziness and I need a way to create a tree with a nullptr.

Regardless, we will need an is_nullptr function and check it in eval and get. I suppose the only thing up in the air is how eval should handle nullptrs

**Comment by kgioioso** [comment]
(I briefly considered implementing laziness but I think that might be a task that takes longer than 2 weeks for me...)

**Comment by keithw** [comment]
Ooh, I think I just don't love the idea of having "nullptrs" exist at all **if** we can avoid it... I didn't realize it was possible to create a Tree with the "default" null value in it.

How would you feel if we changed `wasm_rt_externref_null_value` so that instead of being the value `{ 0, 0, 0, 0 }`, it's the externref that represents a strict accessible zero-length Blob? That way the default externref is always valid and we can avoid thinking about exceptional values for a little longer.

---

[*] (I do think soon we'll probably need some special Names to represent things like "deterministic trap" and "nondeterministic trap," which will require some special treatment but aren't exactly the same...)

**Comment by kgioioso** [comment]
that works for me

**Comment by kgioioso** [comment]
hmm actually do we want an unset element of a tree to succeed when being evaluated? It seems like we want it to fail.

In general, is there anything stopping a user from putting junk in the externref tables? It seems like if there's junk in there, eval should fail. Similarly, if the values are unset, eval should fail.

**Comment by kgioioso** [comment]
I'm trying to decide if it's easier for the user if an unset element fails or succeeds.

**Comment by keithw** [comment]
I think it would be nice not to have to worry about any "invalid" Objects in the repo.

Which means I don't think we'd want any procedure to be able to create a Tree with "invalid" entries. Which I think gives us two options:

- make the default externref be something valid but harmless (e.g., a zero-length Blob), or
- do a linear scan in `create_tree()` to make sure all entries in the table are valid, and trap if not

Tentatively I think I'd be more inclined towards the first, but I don't think it's 100% obvious.

**Comment by keithw** [comment]
> In general, is there anything stopping a user from putting junk in the externref tables?

In general there's hopefully no way for the procedure to put junk in an externref table, because it can't generate an arbitrary externref. AFAIK the only ways for the Wasm procedure to get an externref are:

- the default value (`wasm_rt_externref_null_value`)
- the parameter that gets passed in to `_fixpoint_apply`
- the return value to some of the Fix API functions, and
- by using the Fix API to attach a tree to an ro table and then retrieving the `externref` entry from the table

This is hopefully how we enforce the containerization/isolation and capability rules (accessible/inaccessible) -- the procedure can only get a "handle" to something passed in or accessible from that.

**Comment by kgioioso** [comment]
is there anything preventing a user from (diabolically) importing a module that returns an externref? We def don't want this behavior, I'm just trying to think through ways that there could be garbage in an externref table

**Comment by keithw** [comment]
In WebAssembly, afaik there's no way for any module to generate an externref other than the default value -- the code can only get one via:

- a function parameter or result
- importing an externref table
- exporting an externref table and having another module write a value into it

I think that's the complete list. :-) Its really an *extern*ref in a strong sense -- they can only originate "external" to the module. (Except for the default value, which we/the wasm2c runtime gets to pick.)

**Pull request merged**
